import type { AppLocale } from "../context/LanguageContext";

export const copy = {
	en: {
		login: {
			header: "Login (skeleton)",
			kicker: "AgriNexus · mobile",
			body: "Email + JWT from apps/backend (dev stub). Catalog loads from Next /api/mobile/courses.",
			email: "Email",
			placeholder: "you@farm.example",
			continue: "Sign in & get token",
			hint: "Token is stored on device (SecureStore / AsyncStorage on web).",
			back: "← Home",
			busy: "Signing in…",
			errorTitle: "Could not sign in",
			errorFallback: "Check EXPO_PUBLIC_BACKEND_URL and that FastAPI is running.",
		},
		academy: {
			header: "My Academy",
			kicker: "AgriNexus Academy",
			heading: "Courses for the farm",
			intro: "Short modules you can finish between seasons — practical checklists, not theory walls.",
			coursesTitle: "Catalog",
			modules: "{{count}} modules",
			lectures: "Lectures",
			openCourse: "Open course",
			notFound: "Course not found",
			backList: "← All courses",
			loading: "Loading catalog from Next…",
			errorTitle: "Could not load catalog",
			retry: "Retry",
			offlineHint: "Showing bundled catalog (Next unreachable).",
			progressLabel: "{{pct}}% done",
			lectureMark: "Mark lecture as studied",
			lectureUnmark: "Mark as not studied",
		},
		home: {
			title: "AgriNexus",
			subtitle: "Mobile app — same roadmap as apps/web.",
			login: "Login",
			academy: "Academy",
			signedInAs: "Signed in as {{email}}",
			signOut: "Sign out",
		},
		welcome: {
			title: "Welcome",
			kicker: "AgriNexus",
			headline: "Sense. Think. Act.",
			lead: "Your pocket copilot for fields, markets, and structured learning.",
			b1: "Academy paths with progress you can track offline.",
			b2: "AI tutor through your Next + FastAPI stack.",
			b3: "A short farm profile so tips match your region.",
			cta: "Continue",
			hasAccount: "I already have an account → Sign in",
		},
		mobOnboarding: {
			title: "Farm setup",
			kicker: "One-time",
			step1Title: "Main crops",
			step1Hint: "Select all that apply.",
			step2Title: "Region & area",
			regionLabel: "Region",
			haLabel: "Total hectares",
			haPlaceholder: "e.g. 120",
			next: "Next",
			back: "Back",
			finish: "Save & Home",
			busy: "Saving…",
			error: "Complete all fields.",
		},
		dashboard: {
			tabTitle: "Home",
			greeting: "Hello",
			guestName: "farmer",
			tagline: "Your fields, markets, and learning in one pocket.",
			quickTutor: "AI Tutor",
			quickTutorSub: "Ask in plain language",
			quickAcademy: "My Academy",
			quickAcademySub: "Courses & progress",
			continueTitle: "Pick up where you left off",
			continueEmpty: "Open a course in Academy and mark lectures as done to see progress here.",
			openCourse: "Open course",
			statsHint: "Tip: keep Next.js running for live catalog and tutor (EXPO_PUBLIC_WEB_ORIGIN).",
		},
		tutor: {
			tabTitle: "Tutor",
			header: "AI Tutor",
			empty: "Ask anything about crops, markets, or weather risk. Answers go through your Next app to the backend.",
			placeholder: "Message…",
			send: "Send",
			sending: "Thinking…",
			errorPrefix: "Could not reply",
			suggestions: "Try asking",
			chip1: "What should I check before topdressing N?",
			chip2: "How do basis and local price differ?",
			chip3: "Drought risk signs in the next 10 days?",
		},
	},
	bg: {
		home: {
			title: "AgriNexus",
			subtitle: "Мобилно приложение — същият път като apps/web.",
			login: "Вход",
			academy: "Академия",
			signedInAs: "Влязъл като {{email}}",
			signOut: "Изход",
		},
		welcome: {
			title: "Добре дошли",
			kicker: "AgriNexus",
			headline: "Усеща. Мисли. Действа.",
			lead: "Помощник в джоба за полета, пазари и структурирано обучение.",
			b1: "Академия с прогрес, който можеш да следиш офлайн.",
			b2: "AI асистент през твоя Next + FastAPI.",
			b3: "Кратък профил на стопанството за съвети според регион.",
			cta: "Напред",
			hasAccount: "Вече имам акаунт → Вход",
		},
		mobOnboarding: {
			title: "Настройка на стопанството",
			kicker: "Еднократно",
			step1Title: "Основни култури",
			step1Hint: "Маркирай всички подходящи.",
			step2Title: "Регион и площ",
			regionLabel: "Регион",
			haLabel: "Общо хектари",
			haPlaceholder: "напр. 120",
			next: "Напред",
			back: "Назад",
			finish: "Запази и към Начало",
			busy: "Запазване…",
			error: "Попълни всички полета.",
		},
		dashboard: {
			tabTitle: "Начало",
			greeting: "Здравей",
			guestName: "стопанин",
			tagline: "Полета, пазари и обучение в джоба.",
			quickTutor: "AI асистент",
			quickTutorSub: "Питай на прост език",
			quickAcademy: "Моята академия",
			quickAcademySub: "Курсове и прогрес",
			continueTitle: "Продължи оттук",
			continueEmpty: "Отвори курс в Академията и отбелязвай лекциите, за да видиш прогрес тук.",
			openCourse: "Отвори курса",
			statsHint: "Съвет: пусни Next.js за жив каталог и tutor (EXPO_PUBLIC_WEB_ORIGIN).",
		},
		tutor: {
			tabTitle: "Асистент",
			header: "AI асистент",
			empty: "Питай за култури, пазари или климатичен риск. Отговорите минават през Next към бекенда.",
			placeholder: "Съобщение…",
			send: "Изпрати",
			sending: "Мисля…",
			errorPrefix: "Няма отговор",
			suggestions: "Опитай",
			chip1: "Какво да проверя преди допълнително азотно торене?",
			chip2: "Как се различават базис и локална цена?",
			chip3: "Знаци за суша в следващите 10 дни?",
		},
		login: {
			header: "Вход (скелет)",
			kicker: "AgriNexus · mobile",
			body: "Имейл + JWT от apps/backend (dev). Каталогът идва от Next /api/mobile/courses.",
			email: "Имейл",
			placeholder: "ti@ferma.example",
			continue: "Вход и токен",
			hint: "Токенът се пази на устройството (SecureStore; в web — AsyncStorage).",
			back: "← Начало",
			busy: "Влизане…",
			errorTitle: "Неуспешен вход",
			errorFallback: "Провери EXPO_PUBLIC_BACKEND_URL и дали FastAPI работи.",
		},
		academy: {
			header: "Моята академия",
			kicker: "AgriNexus Academy",
			heading: "Курсове за стопанството",
			intro: "Кратки модули между сезоните — практични чеклисти, не стени от теория.",
			coursesTitle: "Каталог",
			modules: "{{count}} модула",
			lectures: "Лекции",
			openCourse: "Отвори курса",
			notFound: "Курсът не е намерен",
			backList: "← Всички курсове",
			loading: "Зареждане на каталога от Next…",
			errorTitle: "Каталогът не се зареди",
			retry: "Опитай отново",
			offlineHint: "Показвам вградения каталог (Next е недостъпен).",
			progressLabel: "{{pct}}% готово",
			lectureMark: "Отбележи лекцията като изучена",
			lectureUnmark: "Премахни отбелязването",
		},
	},
} as const;

export type Copy = (typeof copy)["en"];

export function strings(locale: AppLocale) {
	return copy[locale];
}

export function moduleLine(locale: AppLocale, count: number) {
	const raw = copy[locale].academy.modules;
	return raw.replace("{{count}}", String(count));
}
